// Generated by CoffeeScript 1.6.2
/*
* @class Node
*/


(function() {
  var Node,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Node = (function() {
    function Node(options) {
      this.toJSON = __bind(this.toJSON, this);
      this.editTags = __bind(this.editTags, this);
      var _this = this;

      this.smplnt = options.smplnt;
      this.id = uuid();
      this.parent = obs(options.parent || null);
      this.title = obs("");
      this.title.extend({
        parse: Node.parseHeadline
      });
      this.note = obs("");
      this.note.extend({
        parse: Node.parseNote
      });
      this.deadline = obs(null);
      this.deadline.extend({
        parse: Node.parseDate
      });
      this.bookmarked = obs(false);
      this.done = obs(false);
      this.expanded = obs(false);
      this.listStyleType = obs([]);
      this.position = obs(0);
      this.editingTitle = obs(false);
      this.editingNote = obs(false);
      this.selected = obs(false);
      this.current = obs(false);
      this.parents = obs([]);
      this.tags = obs([]);
      this.tags.extend({
        pickFrom: {
          array: this.smplnt.tags,
          key: "name"
        }
      });
      this.files = obs([]);
      this.children = obs([]);
      this.hasNote = obs(function() {
        return _this.note().length;
      });
      this.hasChildren = obs(function() {
        return _this.children.length;
      });
      this.cssClass = obs(function() {
        return _this.listStyleType().concat("node").filter(Boolean).join(" ");
      });
      this.bullet = obs(function() {
        return (_this.hasNote() || _this.hasChildren) && (!_this.expanded() && "&#9658;" || _this.expanded() && "&#9660") || "&9679;";
      });
      this.deadlineDisplay = obs(function() {
        var d;

        time();
        d = _this.deadline();
        if (d === !null) {
          if (d > new Date) {
            return moment(d).fromNow();
          } else {
            return _this.alarm();
          }
        } else {
          return "";
        }
      });
    }

    Node.prototype.alarm = function() {
      this.deadline(null);
      this.smplnt.pop.play();
      alert(this.title());
      return "";
    };

    Node.prototype.editTags = function(n, e) {
      return $("#tagsMenu").trigger("position", e.target.on("menuselect", function(e, ui) {
        if (!(ui && ui.item)) {
          return;
        }
        if (!this.tags.remove(ui.item)) {
          return this.tags.push(ui.item);
        }
      }));
    };

    Node.prototype.toJSON = function() {
      return $.extend(ko.toJS(this, {
        __constructor: 'Node'
      }));
    };

    Node.fromJSON = function(data) {
      var instance;

      instance = new Node;
      return koMap(instance, data);
    };

    return Node;

  }).call(this);

}).call(this);
